
server:
 port: 8080
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.2.100:3306/exam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  username: root
  password: 123.com